import { useEffect, useState } from 'react';
import { Card, CardContent } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Product } from '@/types';
import { ShoppingCart, Heart } from 'lucide-react';
import { useCart } from '@/hooks/useCart';

const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Téléphone Samsung Galaxy',
    description: 'Smartphone haute performance',
    price: 10000,
    portee: 'livrable',
    vendeurId: 'v1',
    vendeur: {
      id: 'v1',
      userId: 'u1',
      storeName: 'Tech Store',
      description: '',
      rating: 4.5,
      reviews: 120,
      verified: true,
      subscription: 'premium',
      createdAt: new Date(),
    },
    ville: 'Matadi',
    category: 'Électronique',
    images: ['https://via.placeholder.com/300'],
    rating: 4.5,
    reviews: 120,
    stock: 5,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: 'Ordinateur Portable Dell',
    description: 'Laptop haute performance pour le travail et le jeu',
    price: 450000,
    portee: 'livrable',
    vendeurId: 'v2',
    vendeur: {
      id: 'v2',
      userId: 'u2',
      storeName: 'Tech Hub',
      description: '',
      rating: 4.7,
      reviews: 95,
      verified: true,
      subscription: 'standard',
      createdAt: new Date(),
    },
    ville: 'Kinshasa',
    category: 'Informatique',
    images: ['https://via.placeholder.com/300'],
    rating: 4.7,
    reviews: 95,
    stock: 8,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: 'Vélo Électrique City',
    description: 'Vélo urbain moderne avec autonomie longue durée',
    price: 1200000,
    portee: 'local',
    vendeurId: 'v3',
    vendeur: {
      id: 'v3',
      userId: 'u3',
      storeName: 'Kin marhé',
      description: '',
      rating: 4.4,
      reviews: 76,
      verified: true,
      subscription: 'free',
      createdAt: new Date(),
    },
    ville: 'Matadi',
    category: 'Sport',
    images: ['https://via.placeholder.com/300'],
    rating: 4.4,
    reviews: 76,
    stock: 2,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: 'Machine à Café Expresso',
    description: 'Cafetière élégante pour des expressos parfaits',
    price: 250000,
    portee: 'livrable',
    vendeurId: 'v4',
    vendeur: {
      id: 'v4',
      userId: 'u4',
      storeName: 'Maison & Cuisine',
      description: '',
      rating: 4.6,
      reviews: 84,
      verified: true,
      subscription: 'premium',
      createdAt: new Date(),
    },
    ville: 'Lubumbashi',
    category: 'Électroménager',
    images: ['https://via.placeholder.com/300'],
    rating: 4.6,
    reviews: 84,
    stock: 10,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

